export const AUTH_CREATE_USER_FAIL = 'AUTH_CREATE_USER_FAIL';
export const AUTH_CREATE_USER_SUCCESS = 'AUTH_CREATE_USER_SUCCESS';
export const AUTH_CREATE_USER_CLEAR_ERROR = 'AUTH_CREATE_USER_CLEAR_ERROR';
