export const AUTH_RESET_PASSWORD_FAIL = 'AUTH_RESET_PASSWORD_FAIL';
export const AUTH_RESET_PASSWORD_SUCCES = 'AUTH_RESET_PASSWORD_SUCCES';
export const AUTH_RESET_PASSWORD_CLEAR_ERROR = 'AUTH_RESET_PASSWORD_CLEAR_ERROR';
